Hotfix: Corrige bug que impedia inputs de serem desabilitados
justapagamentos/justa-angular-library pull request #76
Opened 2020-11-09 13:10 UTC by hugobrancowb

# Versão mask-directive@1.2.1

## :fire: Hotfix
- **Corrige bug que impedia inputs de serem desabilitados.**
  - Corrige bug em que inputs com atributo _disabled: true_ não estavam sendo desabilitados.

2020-11-16 21:04 UTC, raisiqueira requested changes

2020-11-16 21:04 UTC, raisiqueira commented on projects/justa/mask-directive/src/lib/currency-mask.directive.ts
> +    this.control.enable();
@hugobrancowb usa o Renderer2 para desabilitar o input ao invés de acessar o control, desta forma que tá implementado o form não vai ser desabilitado.

2020-11-17 13:59 UTC, raisiqueira approved these changes
Faz o patch da versão para a 1.2.2

2020-11-18 09:06 UTC, felipebonezi approved these changes

2020-11-18 09:07 UTC, merged

2020-11-18 09:08 UTC, felipebonezi commented
@raisiqueira publica no npm, por favor.